name: my_dart_project
description: A new Dart project.
version: 0.1.0
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  test: ^1.16.0  # Add this line for the test package

repository: https://github.com/BrianBett125/my_dart_project  # Add your repo URL here

